### PR TITLE
Added missing _form partial template

### PR DESCRIPTION
**Pull request by shybovycha**
When generating a scaffold with the latest `compound` version, i got exception caught like `Template is missing: scaffold_form.jade`.

### CODE REVIEW

**Comment by 1602** [comment]
How did you get that error? Normally this templated generated by code, not by the template, so this template is not needed and even doesn't works. Have you tested it?

**Comment by shybovycha** [comment]
```
shybovycha@a:~/projects/nodejs/projectname$ compound g crud epanel
exists  app/
exists  app/controllers/
exists  app/helpers/
exists  app/views/
create  app/views/epanels/
exists  app/views/layouts
exists  test/
exists  test/controllers/
create  app/controllers/epanels_controller.js
exists  app/
exists  app/models/
create  app/models/epanel.js
patch   db/schema.js
create  app/views/layouts/epanels_layout.jade

fs.js:338
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/shybovycha/projects/nodejs/projectname/node_modules/jade-ext/templates/scaffold_form.jade'
    at Object.fs.openSync (fs.js:338:18)
    at Object.fs.readFileSync (fs.js:182:15)
    at CrudGenerator.GeneratorUtilities.copyTemplate (/home/shybovycha/projects/nodejs/projectname/node_modules/compound/lib/generators/generator_utils.js:90:28)
    at CrudGenerator.copyFiles.forEach.sourceFileIndex (/home/shybovycha/projects/nodejs/projectname/node_modules/compound/lib/generators/crud_generator.js:198:10)
    at Array.forEach (native)
    at CrudGenerator.copyFiles (/home/shybovycha/projects/nodejs/projectname/node_modules/compound/lib/generators/crud_generator.js:193:5)
    at CrudGenerator.perform (/home/shybovycha/projects/nodejs/projectname/node_modules/compound/lib/generators/crud_generator.js:62:8)
    at Generators.perform (/home/shybovycha/projects/nodejs/projectname/node_modules/compound/lib/generators.js:48:15)
    at /usr/local/lib/node_modules/compound/bin/compound:92:22
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

**Comment by shybovycha** [comment]
And after my fix is being applied:

```
shybovycha@a:~/projects/nodejs/projectname$ compound g crud epanel
exists  app/
exists  app/controllers/
exists  app/helpers/
exists  app/views/
exists  app/views/epanels/
exists  app/views/layouts
exists  test/
exists  test/controllers/
create  app/controllers/epanels_controller.js
exists  app/
exists  app/models/
create  app/models/epanel.js
patch   db/schema.js
create  app/views/layouts/epanels_layout.jade
create  app/views/epanels/_form.jade
create  app/views/epanels/show.jade
create  app/views/epanels/new.jade
create  app/views/epanels/edit.jade
create  app/views/epanels/index.jade
create  app/helpers/epanels.js
create  test/controllers/epanels_controller_test.js
exists  test/test_helper.js
patch   config/routes.js
```

**Comment by shybovycha** [comment]
Actually, i guess you updated the `compoundjs` and did not update the `ejs-ext` nor `jade-ext`. If you think _it should_ - than you'd better check it before saying that.

And one more thing: **exceptions should not interrupt the generation process**. So i should not get half of job done because of someone's mistake in the third-party.

**Comment by 1602** [comment]
Thanks for pointing issue, actually this is a fix:

```
diff --git a/index.js b/index.js
index 1a87971..522dfab 100644
--- a/index.js
+++ b/index.js
@@ -46,7 +46,7 @@ exports.templateText = function (name, data) {
         return fs.readFileSync(exports.template('scaffold_show')).toString().replace('F

         case 'scaffold_form':
-        var form = '';
+        var form = '!= errorMessagesFor(model) \n';
         data.forEach(function (property) {
             switch (property.type) {
                 case 'Boolean':
```

As you can see, it only happens in jade, and only when no properties specified.

**Pull request closed without merging**
